### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/minimed-connect-to-nightscout#9]
Nightscout users who are using mmconnect in NS are now reporting the site crashes every couple days due to running out of memory. The issues seems to be isolated to this module; help checking where the leak is would be great.

**Comment by benceszasz** [comment]
@sulkaharo in my experience this is caused by the missing retryDurationOnAttempt(n) function in carelink.js, which was reported earlier  https://github.com/nightscout/minimed-connect-to-nightscout/issues/5#issue-687862738
